CURRENT_BRANCH_NAME=$(echo $MERGE_MESSAGE | awk -F"'" '{print $2}')
CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME:7}

CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME:${#RELEASE_BRANCH_PREFIX}}
CURRENT_SPRINT=${CURRENT_BRANCH_NAME:3:2}
CURRENT_SQUAD=${CURRENT_BRANCH_NAME:6}
((CURRENT_SPRINT+=1))
printf -v PADDED_SPRINT "%02d" $CURRENT_SPRINT
echo "##vso[task.setvariable variable=mergeBranchName;isreadonly=true;]$SPRINT_BRANCH_PREFIX$PADDED_SPRINT-$CURRENT_SQUAD"




BRANCH_NAME=${BRANCH_NAME:7}
echo "##vso[task.setvariable variable=mergeBranchName;]$BRANCH_NAME"