CURRENT_BRANCH_NAME=$(echo $MERGE_MESSAGE | awk -F"'" '{print $2}')
CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME:7}

CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME:${#RELEASE_BRANCH_PREFIX}}
CURRENT_SPRINT=${CURRENT_BRANCH_NAME:2:2}
CURRENT_SQUAD=${CURRENT_BRANCH_NAME:5}
((CURRENT_SPRINT+=1))
printf -v PADDED_SPRINT "%02d" $CURRENT_SPRINT
CREATE_BRANCH_NAME="$SPRINT_BRANCH_PREFIX$PADDED_SPRINT-$CURRENT_SQUAD"

source ./templates/branch-manipulation/scripts/create-branch.sh
