TAG_WITHOUT_PREFIX=${TAG_NAME#${TAG_PREFIX}}
TAG_WITHOUT_BUILD_NUMBER=${TAG_WITHOUT_PREFIX#*-}
RELEASE_BRANCH_NAME=${RELEASE_PREFIX}${TAG_WITHOUT_BUILD_NUMBER}

echo "##vso[task.setvariable variable=releaseBranchName;]$RELEASE_BRANCH_NAME"
