trigger: none
pr: none

steps:
- template: ../templates/branch-manipulation/prepare-steps.template.yml
  parameters:
    expectedBranchPrefix: release/
- template: ../templates/branch-manipulation/finish-release.template.yml
