trigger:
  branches:
    include:
      - main
pr: none

variables:
- name: mergeBranchName
  value: ''

steps:
- template: ../templates/branch-manipulation/prepare-steps.template.yml
  parameters:
    expectedBranchPrefix: main
- template: ../templates/branch-manipulation/merge-main-to-sprints.template.yml
  parameters:
    squadName: leo
- template: ../templates/branch-manipulation/merge-main-to-sprints.template.yml
  parameters:
    squadName: tigris