trigger: none
pr: none

steps:
- template: ./prepare-steps.template.yml
  parameters:
    expectedBranchPrefix: sprint/
- task: Bash@3
  displayName: Creating release branch
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    targetType: filePath
    filePath: ./scripts/create-branch.sh
  env:
    BRANCH_NAME: $(Build.SourceBranchName)
    BRANCH_PREFIX: release/
- task: Bash@3
  displayName: Creating release branch
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    targetType: filePath
    filePath: ./scripts/create-branch.sh
  env:
    BRANCH_NAME: $(Build.SourceBranchName)
    BRANCH_PREFIX: release/
- task: Bash@3
  displayName: Deleting sprint branch
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    targetType: filePath
    filePath: ./scripts/delete-sprint-branch.sh
  env:
    SPRINT_BRANCH: sprint/$(Build.SourceBranchName)