trigger: none
pr: none

steps:
- template: ../templates/branch-manipulation/prepare-steps.template.yml
  parameters:
    expectedBranchPrefix: sprint/
- template: ../templates/branch-manipulation/start-release.template.yml
