name: Create PR for integration branches

on:
  push:
    branches:
      - integrate-main-to/**/*

jobs:
  createPR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Checks if PR already exists
      id: pr_exists
      run: |
        PR_INFO=$(gh pr list --state open --head $HEAD_BRANCH)
        if [[ "$PR_INFO" =~ ^no[[:space:]]pull[[:space:]]requests.* ]]; then
          echo "result=false" >> $GITHUB_OUTPUT
        else
          echo "result=true" >> $GITHUB_OUTPUT
        fi
      env:
        HEAD_BRANCH: ${{ github.ref_name }}
    - name: Get base branch
      id: base_branch
      if: steps.pr_exists.outputs.result == "false"
      run: echo "branch=${ORIGINAL_BRANCH#integrate-main-to/}" >> $GITHUB_OUTPUT
      env:
        ORIGINAL_BRANCH: ${{ github.ref_name }}
    - name: Create pull request
      if: steps.pr_exists.outputs.result == "false"
      run: gh pr create -B $BASE_BRANCH -H $HEAD_BRANCH --title "Merge branch 'main' into '$BASE_BRANCH'" --body "Pull request automatically created because conflicts existed between 'main' and '$BASE_BRANCH'"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        HEAD_BRANCH: ${{ github.ref_name }}
        BASE_BRANCH: ${{ steps.base_branch.outputs.branch }}
    
    